router ospf
 ospf router-id 1.1.1.1
 network 1.1.1.1/32 area 0
 network 10.1.1.0/30 area 0
 network 10.1.1.4/30 area 0
 network 10.1.1.8/30 area 0

router bgp 65000
 bgp router-id 1.1.1.1
 !
 neighbor 1.1.1.2 remote-as 65000
 neighbor 1.1.1.2 update-source lo
 neighbor 1.1.1.2 route-reflector-client
 !
 neighbor 1.1.1.3 remote-as 65000
 neighbor 1.1.1.3 update-source lo
 neighbor 1.1.1.3 route-reflector-client
 !
 neighbor 1.1.1.4 remote-as 65000
 neighbor 1.1.1.4 update-source lo
 neighbor 1.1.1.4 route-reflector-client
 !
 ! EVP
 address-family l2vpn evpn
  neighbor 1.1.1.2 activate
  neighbor 1.1.1.2 route-reflector-client
  neighbor 1.1.1.3 activate
  neighbor 1.1.1.3 route-reflector-client
  neighbor 1.1.1.4 activate
  neighbor 1.1.1.4 route-reflector-client
 exit-address-family
!
