! OSPFの設定（アンダーレイ）
router ospf
 ospf router-id 1.1.1.4
 network 1.1.1.4/32 area 0
 network 10.1.1.8/30 area 0

! BGPの設定（オーバーレイ連絡網）
router bgp 65000
 bgp router-id 1.1.1.4
 ! 
 ! 司令塔（Spine）をネイバーに指定
 neighbor 1.1.1.1 remote-as 65000
 neighbor 1.1.1.1 update-source lo
 !
 ! EVPNの有効化とVXLAN情報の自動広告
 address-family l2vpn evpn
  neighbor 1.1.1.1 activate
  advertise-all-vni
 exit-address-family
!
